"""Update Table

Revision ID: 169fff063a79
Revises: f77f8c93053b
Create Date: 2024-03-06 03:25:48.518649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169fff063a79'
down_revision = 'f77f8c93053b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collaborators')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_projects_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_projects_owner_id_users'), 'users', ['owner_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=False))
        batch_op.alter_column('due_date',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_tasks_project_id_projects'), 'projects', ['project_id'], ['id'])
        batch_op.drop_column('status')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('role')
        batch_op.drop_column('_password_hash')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_tasks_project_id_projects'), type_='foreignkey')
        batch_op.alter_column('due_date',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('project_id')
        batch_op.drop_column('progress')
        batch_op.drop_column('priority')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_projects_owner_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_projects_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    op.create_table('collaborators',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_collaborators_project_id_projects'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_collaborators_user_id_users'),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    # ### end Alembic commands ###
