"""Add collaborators table

Revision ID: 4dcef24eaf3a
Revises: 6311cb104502
Create Date: 2024-03-04 22:04:25.947779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dcef24eaf3a'
down_revision = '6311cb104502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('deadline', sa.String(), nullable=True))
        batch_op.drop_constraint('fk_projects_owner_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_projects_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('owner_id')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_projects_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_projects_owner_id_users', 'users', ['owner_id'], ['id'])
        batch_op.drop_column('deadline')
        batch_op.drop_column('user_id')
        batch_op.drop_column('project_name')

    # ### end Alembic commands ###
